name: Purge History
on: workflow_dispatch
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Purge folder from history
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # 過去の全履歴から for_gpu を抹消
          git filter-branch --force --index-filter "git rm -r --cached --ignore-unmatch for_gpu" --prune-empty --tag-name-filter cat -- --all
          # 同じURLのまま強制上書きプッシュ
          git push origin --force --all
